LIBS=-lsfml-graphics -lsfml-window -lsfml-system

all: theGame

game.o: game.cpp game.h
	@echo "***compiling game.cpp***"
	g++ -c game.cpp 

theGame: game.o 
	@echo "***Creating Executable*****"
	g++ game.o -o game $(LIBS)

clean: 
	@echo "*****Cleaning game*****"
	rm -rf *.o game
	